name: Sync labels
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/labels.yaml

permissions:
  issues: write

jobs:
  labels:
    name: Run sync

    runs-on: ubuntu-latest

    steps:
      - uses: EndBug/label-sync@da00f2c11fdb78e4fae44adac2fdd713778ea3e8 # v2.3.2
        with:
          # Configuration file
          # NB: URL as a workaround for https://github.com/EndBug/label-sync/issues/204
          config-file: https://raw.githubusercontent.com/getsops/community/main/.github/labels.yaml
          # Strictly declarative
          delete-other-labels: true
